trigger:
- dev
- release/*

# See https://github.com/aspnet/BuildTools
resources:
  repositories:
  - repository: buildtools
    type: github
    endpoint: DotNet-Bot GitHub Connection
    name: aspnet/BuildTools
    ref: refs/heads/dev

phases:
- template: .vsts-pipelines/templates/phases/default-build.yml@buildtools
  parameters:
    agentOs: Windows
    beforeBuild:
      - script: ..\..\tools\update_schema.ps1
      - script: net start w3svc


- template: .vsts-pipelines/templates/phases/default-build.yml@buildtools
  parameters:
    agentOs: macOS
    beforeBuild:
    - script: brew install nginx

- template: .vsts-pipelines/templates/phases/default-build.yml@buildtools
  parameters:
    agentOs: Linux
    beforeBuild:
    - script: apt-get update
    - script: apt-get install libpcre3 libpcre3-dev nginx
